rm(list=ls())
graphics.off()
getwd()
#install.packages("lme4")
library(lme4)
d<-read.table("../data/SparrowSize.txt", header=TRUE)
str(d)
head(d)
summary(d)
table(d$Year)
table(d$BirdID)
table(table(d$BirdID))
require(dplyr)
BirdIDCount <- d %>% count(BirdID,BirdID, sort=TRUE)
BirdIDCount %>% count(n)

